sudo: false
language: ruby
cache:
  bundler: true
services:
  - redis-server
script:
  - bundle exec rspec spec
  - bundle exec bundle audit check
  - bundle exec brakeman -A -q --ensure-latest --no-pager
  - bundle exec standardrb
