sudo: false
language: ruby
rvm:
  - 2.3.8
cache:
  bundler: true
services:
- redis-server
script:
- bundle exec rubocop
- bundle exec rspec spec
- bundle exec bundle audit check
- bundle exec brakeman -A -q --ensure-latest --no-pager
